language: python
sudo: required
dist: xenial
python:
  - "3.6"
  - "3.7"

env:
  - DJANGO=2.0
  - DJANGO=2.1

# command to install dependencies
install:
  - pip install Django==$DJANGO
  - pip install codecov

# command to run tests
script:
    - python -m coverage run ./manage.py test -v3

after_success: codecov
